-- MySQL Script generated by MySQL Workbench
-- Sat Jun 19 09:38:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dh-entregable
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dh-entregable
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dh-entregable` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `dh-entregable` ;


-- -----------------------------------------------------
-- Table `dh-entregable`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dh-entregable`.`users` (
  `id` INT COLLATE utf8mb4_unicode_ci NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` VARCHAR(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dh-entregable`.`notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dh-entregable`.`notes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `description` VARCHAR(255) COLLATE utf8mb4_unicode_ci NULL,
  `user_id` INT COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_usuario_idx` (`user_id` ASC))
--  CONSTRAINT `id_usuario`
--    FOREIGN KEY (`user_id`)
--    REFERENCES `mydb`.`users` (`id`)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION);
    ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dh-entregable`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dh-entregable`.`categories` (
  `id` INT COLLATE utf8mb4_unicode_ci NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



-- -----------------------------------------------------
-- Table `dh-entregable`.`notes_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dh-entregable`.`notes_categories` (
  `id` INT COLLATE utf8mb4_unicode_ci NOT NULL AUTO_INCREMENT,
  `note_id` INT COLLATE utf8mb4_unicode_ci NOT NULL,
  `category_id` INT COLLATE utf8mb4_unicode_ci NULL,
  PRIMARY KEY (`id`),
  INDEX `category_id_idx` (`category_id` ASC),
  INDEX `note_id_idx` (`note_id` ASC))
--  CONSTRAINT `note_id`
--    FOREIGN KEY (`note_id`)
--    REFERENCES `mydb`.`notes` (`id`)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION,
--  CONSTRAINT `category_id`
--    FOREIGN KEY (`category_id`)
--    REFERENCES `mydb`.`categories` (`id`)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- INSERT `dh-entregable`.`users`
-- -----------------------------------------------------


INSERT INTO `dh-entregable`.`users` (`id`, `name`, `email`) VALUES (NULL, 'Franco Spinelli', 'Franco_spinelli@hotmail.com');
INSERT INTO `dh-entregable`.`users` (`id`, `name`, `email`) VALUES (NULL, 'Uriel Sosa', 'uriel@digitalhouse.com');
INSERT INTO `dh-entregable`.`users` (`id`, `name`, `email`) VALUES (NULL, 'Sebastían Rellihan', 'srellihan@digitalhouse.com');
INSERT INTO `dh-entregable`.`users` (`id`, `name`, `email`) VALUES (NULL, 'Matías Heber', 'mheber@digitalhouse.com');
INSERT INTO `dh-entregable`.`users` (`id`, `name`, `email`) VALUES (NULL, 'Javier Herrera', 'javier@digitalhouse.com');

-- -----------------------------------------------------
-- INSERT `dh-entregable`.`notes`
-- -----------------------------------------------------

INSERT INTO `dh-entregable`.`notes` (`id`, `title`, `description`, `user_id`) VALUES (NULL, 'Calentamiento global', 'El calentamiento global es todo un tema.', '1');
INSERT INTO `dh-entregable`.`notes` (`id`, `title`, `description`, `user_id`) VALUES (NULL, 'Elecciones en Peru', 'Elecciones en Perú: con el conteo de votos al 100%, Castillo supera a Fujimori en las presidenciales, aunque aún no se ha declarado a un ganador.', '1');
INSERT INTO `dh-entregable`.`notes` (`id`, `title`, `description`, `user_id`) VALUES (NULL, '¿PHP o JavaScript?', 'La principal diferencia es que PHP se inicia en el servidor, lo que genera un código HTML que se envía como respuesta del navegador. JavaScript se inicia en el navegador, no en el servidor.', '2');
INSERT INTO `dh-entregable`.`notes` (`id`, `title`, `description`, `user_id`) VALUES (NULL, 'La historia de Kobu', 'Kobu es mi gato y te saluda, te dice el calendario de la cursada, el link de zoom y otras cosas.', '2');
INSERT INTO `dh-entregable`.`notes` (`id`, `title`, `description`, `user_id`) VALUES (NULL, 'Consejos de cursada by Sebis', 'Sean prolijos a la hora de codear, lean mucha data técnica cuando no entiendan algo, suban todo a su repositorio remoto.', '3');

-- -----------------------------------------------------
-- INSERT `dh-entregable`.`notes_categories`
-- -----------------------------------------------------

INSERT INTO `dh-entregable`.`notes_categories` (`id`, `note_id`, `category_id`) VALUES (NULL, '1', '1');
INSERT INTO `dh-entregable`.`notes_categories` (`id`, `note_id`, `category_id`) VALUES (NULL, '2', '2');
INSERT INTO `dh-entregable`.`notes_categories` (`id`, `note_id`, `category_id`) VALUES (NULL, '3', '3');
INSERT INTO `dh-entregable`.`notes_categories` (`id`, `note_id`, `category_id`) VALUES (NULL, '4', '3');
INSERT INTO `dh-entregable`.`notes_categories` (`id`, `note_id`, `category_id`) VALUES (NULL, '5', '3');
INSERT INTO `dh-entregable`.`notes_categories` (`id`, `note_id`, `category_id`) VALUES (NULL, '3', '1');
INSERT INTO `dh-entregable`.`notes_categories` (`id`, `note_id`, `category_id`) VALUES (NULL, '3', '4');
INSERT INTO `dh-entregable`.`notes_categories` (`id`, `note_id`, `category_id`) VALUES (NULL, '5', '4');

-- -----------------------------------------------------
-- INSERT `dh-entregable`.`categories`
-- -----------------------------------------------------

INSERT INTO `dh-entregable`.`categories` (`id`, `name`) VALUES (NULL, 'Mundo');
INSERT INTO `dh-entregable`.`categories` (`id`, `name`) VALUES (NULL, 'Política');
INSERT INTO `dh-entregable`.`categories` (`id`, `name`) VALUES (NULL, 'Cursada');
INSERT INTO `dh-entregable`.`categories` (`id`, `name`) VALUES (NULL, 'Programación');



-- -----------------------------------------------------
-- TESTING
-- -----------------------------------------------------

-- SELECT users.name as 'Usuario', email as 'Email', title as 'Título', description as 'Descripción', categories.name as 'Categoría', create_time as 'Creación', update_time 'Modificación'
-- FROM users
-- INNER JOIN notes
-- ON notes.user_id = users.id
-- INNER JOIN notes_categories
-- on notes_categories.note_id = notes.id
-- INNER JOIN categories
-- ON notes_categories.category_id = categories.id
-- ORDER BY users.name, notes.title, notes.description;

